services:
  cutter-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cutter_backend
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    expose:
      - "8000"

  cutter-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cutter_frontend
    restart: unless-stopped
    depends_on:
      - cutter-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "8083:80"
